PARAM:
  semilla: 662287
  input_exps: TS-0002
  meta:
    script: /src/wf-etapas/z2201_HT_lightgbm_gan.r
  lgb_crossvalidation_folds: 5.0
  train:
    clase01_valor1:
    - BAJA+2
    - BAJA+1
    positivos: BAJA+2
    gan1: 117000.0
    gan0: -3000.0
    meseta: 401.0
  lgb_param:
    boosting: gbdt
    objective: binary
    metric: custom
    first_metric_only: yes
    boost_from_average: yes
    feature_pre_filter: no
    force_row_wise: yes
    verbosity: -100.0
    max_depth: -1
    min_gain_to_split: 0.0
    min_sum_hessian_in_leaf: 0.001
    lambda_l1: 0.0
    lambda_l2: 0.0
    max_bin: 31
    num_iterations: 9999.0
    bagging_fraction: 1.0
    pos_bagging_fraction: 1.0
    neg_bagging_fraction: 1.0
    is_unbalance: no
    scale_pos_weight: 1.0
    drop_rate: 0.1
    max_drop: 50.0
    skip_drop: 0.5
    extra_trees: no
    learning_rate: 0.2
    feature_fraction: 0.5
    min_data_in_leaf: 80.0
    num_leaves:
    - '20'
    - '100'
    - integer
  bo_iteraciones: 100.0
time:
  start: 20241007 160420
  end: 20241007 165146
train:
  ncol: 627
  nrow: 60460
  periodos: 9
validate:
  ncol: 627
  nrow: 32990
  periodos: 1
test:
  ncol: 629
  nrow: 33053
  periodos: 1
crossvalidation: no
BO:
  iteracion_actual: 104
  mejor:
    iteracion: 14
    ganancia: 1.205896e+07
    metrica: 1.205896e+07
    arboles: 101
ganancia_max: 1.205896e+07
